name = "Test Trigger"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "Test Trigger_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "Test Trigger.wasm"
command = "npm run build:release"
